import { existsSync } from "node:fs";
import { dirname, isAbsolute, join, resolve } from "node:path";
import { pathToFileURL } from "node:url";

interface ModelLike {
	id: string;
	name: string;
	api: string;
	provider: string;
	baseUrl: string;
	reasoning: boolean;
	input: string[];
	cost: { input: number; output: number; cacheRead: number; cacheWrite: number };
	contextWindow: number;
	maxTokens: number;
	[key: string]: unknown;
}

function findReferenceRoot(): string {
	const configured = process.env.PI_AI_REF;
	if (configured) {
		const candidate = isAbsolute(configured) ? configured : resolve(process.cwd(), configured);
		if (!existsSync(join(candidate, "src/models.generated.ts"))) {
			throw new Error(`PI_AI_REF does not contain src/models.generated.ts: ${candidate}`);
		}
		return candidate;
	}

	const documentedRelative = resolve(import.meta.dir, "../../../.references/pi/packages/ai");
	if (existsSync(join(documentedRelative, "src/models.generated.ts"))) return documentedRelative;

	let current = import.meta.dir;
	while (dirname(current) !== current) {
		const candidate = join(current, ".references/pi/packages/ai");
		if (existsSync(join(candidate, "src/models.generated.ts"))) return candidate;
		current = dirname(current);
	}

	const workstationFallback = "/home/alpha/exp/pi-rust/.references/pi/packages/ai";
	if (existsSync(join(workstationFallback, "src/models.generated.ts"))) return workstationFallback;
	throw new Error("Unable to locate the pi packages/ai reference; set PI_AI_REF");
}

function rustString(value: string): string {
	return JSON.stringify(value);
}

function rustRawString(value: string): string {
	let hashes = "";
	while (value.includes(`"${hashes}`)) hashes += "#";
	return `r${hashes}"${value}"${hashes}`;
}

function stableJson(value: unknown): string {
	return JSON.stringify(value, (_key, item: unknown) => {
		if (item === null || Array.isArray(item) || typeof item !== "object") return item;
		return Object.fromEntries(
			Object.entries(item as Record<string, unknown>).sort(([left], [right]) =>
				left < right ? -1 : left > right ? 1 : 0,
			),
		);
	});
}

const referenceRoot = findReferenceRoot();
const providersDir = join(referenceRoot, "src/providers");
const generatedSource = await Bun.file(join(referenceRoot, "src/models.generated.ts")).text();
const canonicalProviders = new Set(
	[...generatedSource.matchAll(/^\s*"([^"]+)":\s*[A-Z0-9_]+_MODELS,/gm)].map((match) => match[1]),
);
const files = [...new Bun.Glob("*.models.ts").scanSync({ cwd: providersDir, absolute: true })].sort();

const models: ModelLike[] = [];
for (const file of files) {
	const provider = file.slice(file.lastIndexOf("/") + 1, -".models.ts".length);
	if (!canonicalProviders.has(provider)) continue;
	// The module path is discovered from the canonical provider registry at runtime,
	// so a static import cannot represent the complete generated catalog.
	const module = (await import(pathToFileURL(file).href)) as Record<string, unknown>;
	const catalog = Object.values(module).find(
		(value): value is Record<string, ModelLike> =>
			typeof value === "object" && value !== null && !Array.isArray(value),
	);
	if (!catalog) throw new Error(`No model catalog export found in ${file}`);
	for (const model of Object.values(catalog)) models.push(model);
}

models.sort((a, b) => {
	const providerOrder = a.provider < b.provider ? -1 : a.provider > b.provider ? 1 : 0;
	if (providerOrder !== 0) return providerOrder;
	return a.id < b.id ? -1 : a.id > b.id ? 1 : 0;
});
if (!models.some((model) => model.provider === "anthropic")) throw new Error("Anthropic catalog is empty");
if (!models.some((model) => model.provider === "openai")) throw new Error("OpenAI catalog is empty");

const lines = [
	"// @generated by scripts/gen-models.ts; do not edit.",
	"use crate::models::ModelEntry;",
	"",
	"pub static MODELS: &[ModelEntry] = &[",
];
for (const model of models) {
	const raw = stableJson(model);
	lines.push("    ModelEntry {");
	lines.push(`        provider: ${rustString(model.provider)},`);
	lines.push(`        id: ${rustString(model.id)},`);
	lines.push(`        name: ${rustString(model.name)},`);
	lines.push(`        api: ${rustString(model.api)},`);
	lines.push(`        base_url: ${rustString(model.baseUrl)},`);
	lines.push(`        reasoning: ${model.reasoning},`);
	lines.push(`        context_window: ${model.contextWindow},`);
	lines.push(`        max_tokens: ${model.maxTokens},`);
	lines.push(`        raw_json: ${rustRawString(raw)},`);
	lines.push("    },");
}
lines.push("];", "");

const output = resolve(import.meta.dir, "../crates/pi-ai/src/models_generated.rs");
await Bun.write(output, lines.join("\n"));
// CI zero-diff gate: bun scripts/gen-models.ts && git diff --exit-code crates/pi-ai/src/models_generated.rs
console.log(`Generated ${models.length} models from ${canonicalProviders.size} providers at ${output}`);
